language: elixir
elixir:
- 1.4.2
- 1.3.4
otp_release:
- 19.2
- 19.1
- 18.2.1
env:
  matrix:
  - MIX_ENV=test
  global:
    secure: efljSjECgQPORvj1pPNSRYhFitDfQW+uICdXEtMh2gr6vqtrhQJwdD0DH61Fn+QK92t2tuOUkN73zbhEqbavTh0fCACbQ746crka4bRTgoNa80VBJWhOLEVzGpDbk8/6feTFfvpodK6NobgkzcieoBSBF8atBag2V9zrFg648kXsp1fQaUbjZdl8KLLu3oQ6/R9cMkAAF2vfnzAG37Uos0GsgVdqxfpL7VXscFbWoC/W8wtffhYlye9WZRe0nZC624lZHR5anMijAFsnYeaU/Kg5BKjaCQVaYi0xoEimMLzrzhEf6Dh6xCUxa2Bd/FLCCNXrr9Kt+AT1ZvA4H6KpcC3xrmw8q2Q060Ir+DEcv8Bkut6nUAOrdrVDkhaQIya+XAEpQ9dqEpqKf10D2Cik1TVoz4CwrtP0ny0l/SY8VmRGBgiv7RA07Ugtr1ZN5APCZdBGfXnxsPdTtxQ8Kgeey5x3hXdGZA48JrqSpzlb96oRyi7S5wWP26s74OWxCMSrl908KH/PjUlSRsfa/o78nnxNnsmykTyPdhLBd1j4rIzLvFKb4hejtdJahNPaip12+LavCJiTijppztZw8Ko0vwnb5D7HV6Tx93zTn5SOQLldsq6rEwmwaYGY3t1aRPPymvHhVpnnUmE2ArkyxTtt/zh2m3c5nqA7EFvpZai9eOs=
script: mix coveralls.travis
notifications:
  email: false
